FOLDERS_TO_BACKUP = ['C:\\', 'd:\\']
EXCLUDED_PATHS = ['C:\\Program Files (x86)', 'C:\\Program Files', 'C:\\Windows']
BACKUP_DESTINATION = 'PCBACKUP'
PROGRESS_INTERNALS = 1
WORKERS = 30
UPLOAD_RETRIES = 3
LOG_LEVEL = 'INFO' # DEBUG, INFO, ERROR


#FOLDERS_TO_BACKUP = ['C:\\backup']
#BACKUP_DESTINATION = 'PCBACKUPTEMP'
#WORKERS = 1
#LOG_LEVEL = 'DEBUG'
