FOLDERS_TO_BACKUP = ['C:\\', 'd:\\']
EXCLUDED_PATHS = ['C:\\Program Files (x86)', 'C:\\Program Files', 'C:\\Windows']
BACKUP_DESTINATION = 'PCBACKUP'
PROGRESS_INTERNALS = 1
DRIVE_SCAN_PAGE_SIZE = 100
WORKERS = 30
UPLOAD_RETRIES = 3
LOG_LEVEL = 'INFO' # DEBUG, INFO, ERROR

FOLDERS_TO_BACKUP = ['C:\\adb']
BACKUP_DESTINATION = 'PCBACKUPTEMP'
WORKERS = 30
DRIVE_SCAN_PAGE_SIZE = 100
LOG_LEVEL = 'INFO'
